# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/phoenix/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/phoenix

PRODUCT_COPY_FILES += \
    vendor/lge/phoenix/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/lge/phoenix/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/lge/phoenix/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt
